name: Test Files Naming Check

on:
  push

jobs:
  check-test-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check added file names
        run: |
          git diff --name-only HEAD~1 HEAD | grep 'test_' || echo "No test files added."
      